import { Footer } from '@/components/Footer'
import { Navbar } from '@/components/Navbar'
import { Providers } from '@/lib/providers'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='es' suppressHydrationWarning>
      <head>
        <link rel='shortcut icon' href='/notes.svg' type='image/svg+xml' />
      </head>
      <body
        className={`${geistSans.className} ${geistMono.className} antialiased flex flex-col min-h-screen`}
      >
        <Providers>
          <Navbar />
          <main className='flex-1'>{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
