import './globals.css'
import Navbar from '@/components/Navbar'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <body>
        {/* Esta navegación se mostrará en cualquier página de la aplicación */}
        <Navbar />
        {children}
      </body>
    </html>
  )
}
